version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-18-bullseye
    volumes:
      - ../..:/workspaces/assembly_tracker:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # We use network_mode: service:db so we can access localhost:5432
    network_mode: service:db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assembly_tracker

volumes:
  postgres-data:
